const constants = {
    UPDATE_USER : "UPDATE_USER" ,
    UPDATE_USER_CONNECTION : "UPDATE_USER_CONNECTION",
    UPDATE_USERFB : "UPDATE_USERFB",
    UPADTE_PHOTOS : "UPDATE_PHOTOS",
    UPDATE_CHECKED_PHOTO : "UPDATE_CHECKED_PHOTO",
    ADD_PHOTO: "ADD_PHOTO",
    REMOVE_PHOTO: "REMOVE_PHOTO",
    REMOVE_ALL_PHOTOS : "REMOVE_ALL_PHOTOS",
    UPDATE_SIGNUP : "UPDATE_SIGNUP",
    UPDATE_SIGNUP_FIELD_ERROR : "UPDATE_SIGNUP_FIELD_ERROR",
    UPDATE_SIGNIN : "UPDATE_SIGNIN",
    UPDATE_LOADING : "UPDATE_LOADING",
    UPDATE_LOADED : "UPDATE_LOADED",
    UPDATE_UPLOAD : "UPDATE_UPLOAD",
    UPDATE_UPLOADED : "UPDATE_UPLOADED",
    UPDATE_LOADING_LOADED : "UPDATE_LOADING_LOADED",
    UPDATE_LOADED_UPLOAD : "UPDATE_LOADED_UPLOAD",
    UPDATE_LOADING_UPLOADED : "UPDATE_LOADING_UPLOADED",
    RESET_USER_DASHBOARD : "RESET_USER_DASHBOARD",
    UPDATE_ERROR_USER_DASHBOARD : "UPDATE_ERROR_USER_DASHBOARD",
    UPDATE_LIGHTBOX : "UPDATE_LIGHTBOX",
    UPDATE_PHOTO_INDEX : "UPDATE_PHOTO_INDEX"

}

export default constants;
