const constants = {
    UPDATE_USER : "UPDATE_USER" ,
    UPDATE_USER_CONNECTION : "UPDATE_USER_CONNECTION",
    UPDATE_USERFB : "UPDATE_USERFB",
    UPADTE_PHOTOS : "UPDATE_PHOTOS",
    UPDATE_CHECKED_PHOTO : "UPDATE_CHECKED_PHOTO",
    ADD_PHOTO: "ADD_PHOTO",
    REMOVE_PHOTO: "REMOVE_PHOTO",
    REMOVE_ALL_PHOTOS : "REMOVE_ALL_PHOTOS",
    UPDATE_SIGNUP : "UPDATE_SIGNUP",
    UPDATE_SIGNUP_FIELD_ERROR : "UPDATE_SIGNUP_FIELD_ERROR",
    UPDATE_SIGNIN : "UPDATE_SIGNIN",

}

export default constants;
